### PR TITLE
Adding the link to my raft repository

### PR DESCRIPTION
**Pull request by dushyant89**
https://github.com/dushyant89/raft-angular

### CODE REVIEW

**Comment by ongardie** [comment]
Thanks @dushyant89. Can you add a license so others know how they may use this code? https://help.github.com/articles/licensing-a-repository/

**Comment by dushyant89** [comment]
Hey @ongardie i have added the license file. Thanks for pointing out.

**Comment by dushyant89** [comment]
@ongardie i am also giving a talk about RAFT at [Angular Camp](https://github.com/AngularCamp/angularcamp.org/issues/122)

**Comment by ongardie** [comment]
Awesome, good luck at Angular Camp and enjoy Barcelona :)

**Comment by dushyant89** [comment]
thanks @ongardie :)

**Pull request merged**
