### PR TITLE
Add resetius/miniraft-cpp

### PR DESCRIPTION
**Pull request by resetius**

### CODE REVIEW

**Comment by ongardie** [comment]
Thanks @resetius. Please sort the new entry by its repoURL.

**Comment by ongardie** [comment]
thanks!

**Comment by resetius** [comment]
Thank you very much! How do you update the stars column?

**Comment by ongardie** [comment]
A cron job that runs fetch_repo_info.py should get the updated star count at least daily.

**Comment by ongardie** [comment]
Nowadays we could probably use Github Actions to do this somehow, but I think/hope the cron job has been working.

**Pull request merged**
