### PR TITLE
Add eliben/raft to implementations.json

### PR DESCRIPTION
**Pull request by eliben**

### CODE REVIEW

**Comment by ongardie** [comment]
Thanks @eliben. I think you have a trailing comma on line 999 that's invalid JSON, so the automated checks are failing.

**Comment by eliben** [comment]
Thanks for taking a look quickly, @ongardie 
It should be fixed now

**Comment by ongardie** [comment]
@eliben thanks but please see the new check (`check.py`) error

**Comment by eliben** [comment]
Thanks for merging, @ongardie 
It was still on my radar to fix it after I'm back from vacation next week :-) I hope it wasn't anything too time consuming

**Comment by ongardie** [comment]
No problem @eliben. It was easy, so I just went ahead and got it done. Enjoy your vacation!

**Pull request merged**
