### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by baotiao**
add Qihoo raft implementation

### CODE REVIEW

**Comment by ongardie** [comment]
Hey @baotiao, thanks for the PR. One question: the license file over in the repo says GPL3--which is it?

**Comment by baotiao** [comment]
@ongardie  I have added the license file in the repo

**Comment by ongardie** [comment]
@baotiao ok, could you update the license name in this patch (from "MIT" to "GPL3"), along with the name of the project (now apparently "Floyd")?

**Comment by baotiao** [comment]
@ongardie   I have fixed what you said. Thank you

**Comment by ongardie** [comment]
thanks

**Pull request merged**
