### PR TITLE
Add LENSHOOD/go-raft implementation

### PR DESCRIPTION
**Pull request by LENSHOOD**

### CODE REVIEW

**Comment by ongardie** [comment]
Thanks @LENSHOOD. For `check.py`, please move the implementation up in the array so that it's sorted by repoURL. It should go right before `MicroRaft/MicroRaft`.

**Comment by ongardie** [comment]
Merged, thanks

**Comment by LENSHOOD** [comment]
@ongardie

**Comment by LENSHOOD** [comment]
@ongardie 
Thanks!

**Pull request merged**
